version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
permissions:
  - object: scripts/
    owner: ec2-user
    group: ec2-user
    mode: 755
  - object: scripts/logging.sh
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/run.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/logging.sh
      timeout: 60
      runas: ec2-user
