name: Build and Push to S3 Bucket

on:
  push:
    paths:
      - "loadtest-frontend/**"
      - ".github/workflows/build-and-push-to-bucket.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup npm credentials
        # GitHub Secrets에 저장된 .npmrc 내용을 사용자 홈 디렉토리의 .npmrc에 작성합니다.
        run: echo "${{ secrets.NPMRC }}" > loadtest-frontend/.npmrc

      - name: Setup FRONTEND_ENV
        # GitHub Secrets에 저장된 FRONTEND_ENV 값을 loadtest-frontend/.env.local 파일에 작성합니다.
        run: echo "${{ secrets.FRONTEND_ENV }}" > loadtest-frontend/.env.local

      - name: Install dependencies
        working-directory: loadtest-frontend
        run: npm install

      - name: Build project
        working-directory: loadtest-frontend
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2 # 사용하고자 하는 AWS 리전을 입력하세요

      - name: Upload build files to S3
        run: |
          aws s3 sync loadtest-frontend/out s3://${{ vars.S3_BUCKET_NAME }}/frontend --delete
