name: Deploy to EC2 with CodeDeploy

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: latest
  AWS_REGION: ap-northeast-2

jobs:
  deploy:
    name: Deploy Backend to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{env.AWS_REGION}}

      #- name: Login to Amazon ECR
      #  run: |
      #    aws ecr get-login-password --region ${{env.AWS_REGION}} \
      #      | docker login --username AWS --password-stdin ${{ secrets.ECR_BACKEND_REGISTRY }}

      #- name: Build and push Docker image to ECR
      #  run: |
      #    docker build -t ${{ secrets.ECR_BACKEND_REGISTRY }}/${{ secrets.ECR_BACKEND_REPOSITORY }}:$IMAGE_TAG .
      #    docker push ${{ secrets.ECR_BACKEND_REGISTRY }}/${{ secrets.ECR_BACKEND_REPOSITORY }}:$IMAGE_TAG

      - name: Zip deployment package
        working-directory: loadtest-infra/prod
        run: |
          zip -r buha-deploy.zip appspec.yml scripts/

      - name: Upload to S3
        run: |
          aws s3 cp loadtest-infra/prod/buha-deploy.zip \
            s3://${{ secrets.S3_CODEDEPLOY_BUCKET }}/buha-deploy.zip

      - name: Trigger CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.CODEDEPLOY_APP }} \
            --deployment-group-name ${{ secrets.CODEDEPLOY_GROUP }} \
            --s3-location bucket=${{ secrets.S3_CODEDEPLOY_BUCKET }},key=buha-deploy.zip,bundleType=zip \
            --deployment-config-name CodeDeployDefault.OneAtATime
